import Head from 'next/head'
import Window from "components/Window"
import Desktop from "components/Desktop"
import TaskBar from "components/Taskbar"
import AppLocalStorage from "components/App/Util/LocalStorage"
import Storage from "components/Storage"

export default function Home() {
  return (
    <>
      <Head>
        <title>System Concepts 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Window.Stack>
        <Desktop>
          <Storage>
            <Window.State label="Title">
              <Window>
              </Window>
            </Window.State>
            <Window.State label="Title 2" center>
              <Window>
              </Window>
            </Window.State>
            <AppLocalStorage />
          </Storage>
        </Desktop>
        <TaskBar />
      </Window.Stack>
    </>
  )
}
